name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.0'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run package

      - name: Generate report
        run: npm run report

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: dist/bundle.js

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Report
          path: report.txt